/**
 * Guards for the two facts about a build that living in two files lets drift.
 *
 * WHY THIS EXISTS. qialike never forks deepseek-harness: the build reads each
 * harness package's built `lib/` out of a checkout and applies its anchored
 * patches to it, and it refuses a checkout outside
 * `HARNESS_VERSION_MIN .. HARNESS_VERSION_MAX`. CI has to clone a harness to
 * build at all, and it picks that clone by a tag of its own (`HARNESS_REF`).
 *
 * Those two numbers are the same fact written twice, in two languages, in two
 * files that nothing else compares. Let them diverge and CI quietly validates
 * the build against a harness the build would not accept (or, worse, against one
 * it accepts but was never re-validated on) — a green run that means less than it
 * appears to. That is not hypothetical: the 0.1.5 -> 0.1.7 upgrade broke seven
 * classes of incompatibility and had to be found by hand, and
 * `CONTRIBUTING.md` had been advertising a stale window for exactly this reason.
 *
 * The same argument applies to the embedded version the sidebar reports: it is
 * regenerated from the detected checkout on every build, so a committed value
 * that disagrees with `HARNESS_VERSION_MAX` means the tree was built against
 * something other than what it documents.
 *
 * Run with `bun test tests/release-consistency.test.ts`.
 *
 * @module qialike/release-consistency-test
 */

import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const REPO = new URL('..', import.meta.url).pathname.replace(/\/$/, '')
const read = (path: string): string => readFileSync(`${REPO}/${path}`, 'utf8')

/** The value of a `const NAME = '…'` declaration in a source file. */
function constString(source: string, name: string): string {
  const match = source.match(new RegExp(`^const ${name} = '([^']+)'`, 'm'))
  if (!match) throw new Error(`release-consistency: ${name} not found`)
  return match[1]
}

/** The `HARNESS_REF:` value from the CI workflow's `env:` block. */
function harnessRef(source: string): string {
  const match = source.match(/^\s*HARNESS_REF:\s*(\S+)\s*$/m)
  if (!match) throw new Error('release-consistency: HARNESS_REF not found in the CI workflow')
  return match[1]
}

const BUILD = read('apps/tui-bin/build.mjs')
const CI = read('.github/workflows/ci.yml')

describe('the harness version is one fact, wherever it is written', () => {
  test('CI validates against the release the build accepts', () => {
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    // CI names the tag (`dsh-v0.1.7-alpha.2`); the build names the version. The
    // tag prefix is upstream's convention, so compare the version part only —
    // but require the tag to actually carry it, or a typo would pass.
    const ref = harnessRef(CI)
    expect(ref, `HARNESS_REF should be dsh-v${max}`).toBe(`dsh-v${max}`)
  })

  test('the committed embedded version is the one the build enforces', () => {
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    // Regenerated by every build; a stale value means the tree documents a
    // harness it was not built against.
    expect(read('packages/qialike-app/src/harness-version.ts')).toContain(JSON.stringify(max))
  })

  test('the version range is well-formed and ordered', () => {
    const min = constString(BUILD, 'HARNESS_VERSION_MIN')
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    for (const [name, v] of [['HARNESS_VERSION_MIN', min], ['HARNESS_VERSION_MAX', max]] as const) {
      expect(v, `${name} should look like a version`).toMatch(/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/)
    }
    // Compared on the numeric triples: a string comparison would order
    // `0.1.10` before `0.1.9` and let a genuinely inverted range pass.
    const parts = (v: string): number[] => v.split('-')[0].split('.').map(Number)
    const [a, b] = [parts(min), parts(max)]
    for (let i = 0; i < 3; i += 1) {
      if (a[i] !== b[i]) {
        expect(a[i], `MIN (${min}) must not exceed MAX (${max})`).toBeLessThan(b[i])
        return
      }
    }
    // Equal triples: only a prerelease difference is left, which is fine — the
    // range is then a single release line.
    expect(min).toBeLessThanOrEqual(max)
  })
})

describe('the version the tree claims is the version it ships', () => {
  test('all three package.json files agree', () => {
    const versions = ['package.json', 'packages/qialike-app/package.json', 'apps/tui-bin/package.json']
      .map((p) => JSON.parse(read(p)) as { name: string; version: string })
    const [root, ...rest] = versions
    for (const pkg of rest) {
      // The release scripts abort on a mismatch too, but only when someone runs
      // one; this catches it on the commit that introduces it.
      expect(pkg.version, `${pkg.name} disagrees with ${root.name}`).toBe(root.version)
    }
    expect(root.version).toMatch(/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/)
  })
})
