/**
 * Guards for the two facts about a build that living in two files lets drift.
 *
 * WHY THIS EXISTS. qialike never forks deepseek-harness: the build reads each
 * harness package's built `lib/` out of a checkout and applies its anchored
 * patches to it, and it refuses a checkout outside
 * `HARNESS_VERSION_MIN .. HARNESS_VERSION_MAX`. CI has to clone a harness to
 * build at all, and it picks that clone by a tag of its own (`HARNESS_REF`).
 *
 * Those two numbers are the same fact written twice, in two languages, in two
 * files that nothing else compares. Let them diverge and CI quietly validates
 * the build against a harness the build would not accept (or, worse, against one
 * it accepts but was never re-validated on) — a green run that means less than it
 * appears to. That is not hypothetical: the 0.1.5 -> 0.1.7 upgrade broke seven
 * classes of incompatibility and had to be found by hand, and
 * `CONTRIBUTING.md` had been advertising a stale window for exactly this reason.
 *
 * The same argument applies to the embedded version the sidebar reports: it is
 * regenerated from the detected checkout on every build, so a committed value
 * that disagrees with `HARNESS_VERSION_MAX` means the tree was built against
 * something other than what it documents.
 *
 * Run with `bun test tests/release-consistency.test.ts`.
 *
 * @module qialike/release-consistency-test
 */

import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const REPO = new URL('..', import.meta.url).pathname.replace(/\/$/, '')
const read = (path: string): string => readFileSync(`${REPO}/${path}`, 'utf8')

/** The value of a `const NAME = '…'` declaration in a source file. */
function constString(source: string, name: string): string {
  const match = source.match(new RegExp(`^const ${name} = '([^']+)'`, 'm'))
  if (!match) throw new Error(`release-consistency: ${name} not found`)
  return match[1]
}

/** The `HARNESS_REF:` value from the CI workflow's `env:` block. */
function harnessRef(source: string): string {
  const match = source.match(/^\s*HARNESS_REF:\s*(\S+)\s*$/m)
  if (!match) throw new Error('release-consistency: HARNESS_REF not found in the CI workflow')
  return match[1]
}

const BUILD = read('apps/tui-bin/build.mjs')
const CI = read('.github/workflows/ci.yml')

describe('the harness version is one fact, wherever it is written', () => {
  test('CI validates against the release the build accepts', () => {
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    // CI names the tag (`dsh-v0.1.7-alpha.2`); the build names the version. The
    // tag prefix is upstream's convention, so compare the version part only —
    // but require the tag to actually carry it, or a typo would pass.
    const ref = harnessRef(CI)
    expect(ref, `HARNESS_REF should be dsh-v${max}`).toBe(`dsh-v${max}`)
  })

  test('the committed embedded version is the one the build enforces', () => {
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    // Regenerated by every build; a stale value means the tree documents a
    // harness it was not built against.
    expect(read('packages/qialike-app/src/harness-version.ts')).toContain(JSON.stringify(max))
  })

  test('the version range is well-formed and ordered', () => {
    const min = constString(BUILD, 'HARNESS_VERSION_MIN')
    const max = constString(BUILD, 'HARNESS_VERSION_MAX')
    for (const [name, v] of [['HARNESS_VERSION_MIN', min], ['HARNESS_VERSION_MAX', max]] as const) {
      expect(v, `${name} should look like a version`).toMatch(/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/)
    }
    // Compared on the numeric triples: a string comparison would order
    // `0.1.10` before `0.1.9` and let a genuinely inverted range pass.
    const parts = (v: string): number[] => v.split('-')[0].split('.').map(Number)
    const [a, b] = [parts(min), parts(max)]
    for (let i = 0; i < 3; i += 1) {
      if (a[i] !== b[i]) {
        expect(a[i], `MIN (${min}) must not exceed MAX (${max})`).toBeLessThan(b[i])
        return
      }
    }
    // Equal triples: only a prerelease difference is left, which is fine — the
    // range is then a single release line.
    expect(min).toBeLessThanOrEqual(max)
  })
})

describe('the version the tree claims is the version it ships', () => {
  test('all three package.json files agree', () => {
    const versions = ['package.json', 'packages/qialike-app/package.json', 'apps/tui-bin/package.json']
      .map((p) => JSON.parse(read(p)) as { name: string; version: string })
    const [root, ...rest] = versions
    for (const pkg of rest) {
      // The release scripts abort on a mismatch too, but only when someone runs
      // one; this catches it on the commit that introduces it.
      expect(pkg.version, `${pkg.name} disagrees with ${root.name}`).toBe(root.version)
    }
    expect(root.version).toMatch(/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/)
  })
})

describe('the release asset list is one list', () => {
  test('the build script packages exactly the targets the build compiles', () => {
    // `build-qialike.sh` writes `dist/sha256sums.txt` by iterating its own copy of the
    // target list, while `build.mjs` decides which targets exist. Let them drift and the
    // manifest either omits an asset the release publishes — that platform's install then
    // dies on a missing digest — or names one that was never built. Neither shows up
    // until someone tries to install, which is the worst time to find out.
    const allTargets = BUILD.match(/^const ALL_TARGETS = \[([\s\S]*?)^\]/m)
    if (!allTargets) throw new Error('release-consistency: ALL_TARGETS not found in build.mjs')
    const compiled = [...allTargets[1].matchAll(/'([^']+)'/g)].map((m) => m[1])

    const script = read('scripts/release/build-qialike.sh')
    const declared = script.match(/^\s*ALL_TARGETS=\(([^)]*)\)/m)
    if (!declared) throw new Error('release-consistency: ALL_TARGETS not found in build-qialike.sh')
    const packaged = declared[1].trim().split(/\s+/)

    expect(compiled.length, 'build.mjs should list at least one target').toBeGreaterThan(0)
    // Compared as an ordered list, not a set: the manifest is written in this order, and
    // a stable order is what makes two runs over the same release comparable.
    expect(packaged).toEqual(compiled)
  })
})

describe('the typecheck layout is one fact', () => {
  // WHY THIS EXISTS. `tsconfig.typecheck.json` resolves `@deepseek-ai/*` through 22
  // `paths` entries that hard-code `<repo>/../deepseek-harness`, and CI has to clone a
  // harness to typecheck at all. It used to clone into `$RUNNER_TEMP`: every one of
  // those paths then dangled, TypeScript fell back to node_modules, and the job
  // reported `Cannot find module '@deepseek-ai/cordis'` in files that were fine — a red
  // gate accusing the code of a mistake made by the workflow. So the clone destination
  // is not free to move. Neither is the step order: the typecheck also reads
  // `node_modules/wrap-ansi`, which only the build mirrors in, and without it the three
  // known declarations errors change shape and read as code failures too.
  const TSCONFIG = JSON.parse(read('tsconfig.typecheck.json')) as {
    compilerOptions: { paths: Record<string, string[]> }
  }

  test('every mapped specifier resolves under ../deepseek-harness', () => {
    const entries = Object.entries(TSCONFIG.compilerOptions.paths)
    expect(entries.length).toBeGreaterThan(0)
    for (const [specifier, targets] of entries) {
      for (const target of targets) {
        // Not "a harness somewhere": the config has no way to ask where it is, so the
        // only thing that can keep CI and a developer resolving the SAME files is that
        // both put it here.
        expect(target, `${specifier} must resolve under the sibling harness`).toMatch(/^\.\.\/deepseek-harness\//)
      }
    }
  })

  test('CI checks the harness out where those paths expect it', () => {
    expect(CI).toMatch(/DSH_HARNESS:\s*\$\{\{\s*github\.workspace\s*\}\}\/\.\.\/deepseek-harness/)
    expect(CI).not.toContain('RUNNER_TEMP/deepseek-harness')
  })

  test('CI runs the shared typecheck policy, not a bare tsc', () => {
    // The policy — allow the known `wrap-ansi` declarations gap, fail on anything else —
    // has to be the same one the release gate applies. A bare `tsc` exits 1 on those
    // three, which is how this job stayed red while the gate passed.
    expect(CI).toContain('bash scripts/release/typecheck.sh')
    expect(CI).not.toContain('run: pnpm run typecheck')
    expect(read('scripts/release/test-required.sh')).toContain('bash "$REPO/scripts/release/typecheck.sh"')
    expect(read('scripts/release/typecheck.sh')).toContain('wrap-ansi')
  })

  test('the farm is created before the typecheck that reads it', () => {
    const farm = CI.indexOf('--generate-only')
    const check = CI.indexOf('bash scripts/release/typecheck.sh')
    expect(farm, 'CI should create the resolve farm').toBeGreaterThan(-1)
    expect(check, 'CI should run the shared typecheck policy').toBeGreaterThan(-1)
    expect(farm).toBeLessThan(check)
  })
})

describe('the npm publish workflow is wired to actually finish', () => {
  // WHY THIS EXISTS. Three separate assumptions in these two workflows were wrong or
  // too tight, and each one was invisible until the ones before it stopped failing:
  //   · `publish-npm.yml` used the script's default post-publish window. Publishing
  //     with provenance (OIDC) makes the registry commit the version long after
  //     `npm publish` returns; publishing without it (0.9.0, token/OTP) was under 30 s,
  //     which is why a 30 s window used to be fine. The lag ALSO varies wildly, so the
  //     window has to be sized for the worst case, not the median: run #5 missed x64 by
  //     ~98 s (30 s window), run #7 missed arm64 by ~127 s (120 s window), and run #8
  //     missed the main package by ~630 s (300 s window). Run #8 is the dangerous shape:
  //     that package DID publish — the registry just committed it after the script gave
  //     up — so the job reported failure while npm had the version;
  //   · `ci.yml`'s last step ran `./dist/qialike`, a path the default build NEVER
  //     creates (BUILD_TARGETS=ALL writes `dist/<os>-<arch>/qialike`). It had never
  //     been reached because two earlier steps failed first;
  //   · so the artifacts these two files produce have to be checked for the wiring,
  //     not only the shell logic they call.
  const CI = read('.github/workflows/ci.yml')
  const PUB = read('.github/workflows/publish-npm.yml')
  const SCRIPT = read('scripts/release/publish-npm.sh')

  test('the publish job widens the registry confirmation window', () => {
    // The registry was slower than the script's default by more than 2x. Keep the
    // window generous in the workflow, and keep the order guarantee intact.
    const attempts = /QIALIKE_PUBLISH_CONFIRM_ATTEMPTS:\s*'?(\d+)/.exec(PUB)
    const interval = /QIALIKE_PUBLISH_CONFIRM_INTERVAL:\s*'?(\d+)/.exec(PUB)
    expect(attempts, 'the workflow sets an attempt count').not.toBeNull()
    expect(interval, 'the workflow sets an interval').not.toBeNull()
    const window = Number(attempts![1]) * Number(interval![1])
    // 630 s was the largest measured commit delay; require comfortable headroom over it.
    expect(window, `window ${window}s must clear the measured 630s delay`).toBeGreaterThanOrEqual(900)
    // …and the script's own default must not be the tight 30 s again.
    const dAttempts = /CONFIRM_ATTEMPTS="\$\{QIALIKE_PUBLISH_CONFIRM_ATTEMPTS:-(\d+)\}"/.exec(SCRIPT)
    const dInterval = /CONFIRM_INTERVAL="\$\{QIALIKE_PUBLISH_CONFIRM_INTERVAL:-(\d+)\}"/.exec(SCRIPT)
    expect(dAttempts, 'the script default is parseable').not.toBeNull()
    expect(dInterval, 'the script default is parseable').not.toBeNull()
    expect(Number(dAttempts![1]) * Number(dInterval![1]),
      'the script default window must also clear the measured delay').toBeGreaterThanOrEqual(900)
  })

  test('the confirmation gate still stops before the next package', () => {
    // Widening a timeout must not have turned the gate into a warning: the whole
    // point of confirming is that the MAIN package (whose optionalDependencies name
    // the platform packages) never goes out before they are resolvable.
    expect(SCRIPT).toContain('confirm_published "$pkg" || {')
    expect(SCRIPT).toMatch(/die "停在 \$pkg（发布确认未通过，未推送后续包）"/)
  })

  test('the self-report step does not assume a path the build never creates', () => {
    const step = CI.slice(CI.indexOf('Binary self-report'))
    expect(step, 'the step exists').not.toBe('')
    // `dist/qialike` only exists for a `--single` build; the default is ALL.
    expect(step, 'must not hardcode dist/qialike').not.toMatch(/\.\/dist\/qialike --version/)
    expect(step, 'resolves the host target like smoke.mjs does').toContain('uname -s')
    expect(step, 'names the per-target directory').toContain('dist/${os}-${arch}/qialike')
  })

  test('the default build really does not produce dist/qialike', () => {
    // The premise of the guard above, pinned to the source rather than to a comment:
    // with no `--single`, buildTargets() returns every target.
    const BUILD = read('apps/tui-bin/build.mjs')
    expect(BUILD).toMatch(/args\.includes\('--single'\) \? \[null\] : \[\.\.\.ALL_TARGETS\]/)
    expect(read('package.json')).toContain('"build": "node apps/tui-bin/build.mjs"')
  })
})

describe('the package manager is pinned in exactly one place', () => {
  // WHY THIS EXISTS. `packageManager` is the normative field — Corepack reads it, and
  // pnpm itself self-switches to it (`manage-package-manager-versions` defaults on).
  // CI used to restate the version as a literal in `corepack prepare pnpm@<v>`, a second
  // copy of one fact that nothing compared, so the two could drift silently — the same
  // shape as the `HARNESS_REF` guard above.
  //
  // The lockfile is the other half, and under pnpm 12 it is the half that fails loudly:
  // pnpm 12 records the package manager itself in `packageManagerDependencies` (plus one
  // `@pnpm/exe.<os>` entry per platform), so bumping `packageManager` without regenerating
  // the lockfile makes `pnpm install --frozen-lockfile` — which CI runs — die with
  // ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE. Verified by trying it, on the pnpm 12
  // upgrade that was reverted back to 11.7.0 (user decision). The repo pins 11 today, where
  // the pin lives only in `package.json` and the lockfile records nothing about it — hence
  // the guard states the invariant for whichever major is pinned.
  const CI = read('.github/workflows/ci.yml')
  const PKG = JSON.parse(read('package.json')) as { packageManager?: string }
  const LOCK = read('pnpm-lock.yaml')

  test('CI derives the pnpm version instead of repeating it', () => {
    expect(PKG.packageManager, 'package.json pins the package manager').toMatch(/^pnpm@\d+\.\d+\.\d+/)
    const prepare = CI.split('\n').find((l) => l.includes('corepack prepare'))
    expect(prepare, 'the workflow still activates a pinned pnpm').toBeDefined()
    expect(prepare, 'reads the version out of package.json').toContain('package.json')
    // A literal here would be an unguarded second copy — the thing this test exists for.
    expect(prepare, 'must not hardcode a pnpm version').not.toMatch(/pnpm@\d/)
  })

  test('the lockfile agrees with the pin about which pnpm writes it', () => {
    // Tolerate Corepack's integrity form (`pnpm@1.2.3+sha512.…`), which `corepack use`
    // writes: the lockfile only ever records the bare version.
    const pinned = PKG.packageManager!.replace(/^pnpm@/, '').split('+')[0]
    const major = Number(pinned.split('.')[0])
    // pnpm 12 records the package manager itself in a leading YAML document of its own;
    // pnpm 11 does not. The invariant runs both ways, so it also catches regenerating the
    // lockfile with a pnpm other than the pinned one.
    const specifier = /packageManagerDependencies:\s*\n\s+pnpm:\s*\n\s+specifier:\s*(\S+)/.exec(LOCK)
    if (major >= 12) {
      expect(LOCK, 'pnpm 12 writes packageManagerDependencies').toContain('packageManagerDependencies:')
      expect(specifier, 'pnpm is listed there with a specifier').not.toBeNull()
      expect(specifier![1], 'lockfile and package.json must agree, or --frozen-lockfile fails').toBe(pinned)
    } else {
      expect(specifier, `pnpm ${major} does not write packageManagerDependencies; a lockfile that has one was written by pnpm 12+`).toBeNull()
    }
  })
})
