/**
 * The sidebar's build channel suffix (`QIALIKE_BUILD_MODE`).
 *
 * The channel is BAKED at build time into `packages/qialike-app/src/build-mode.ts`
 * (regenerated by `apps/tui-bin/build.mjs`), so this file tests two things:
 *  - the pure mapping from (version, channel) to the footer suffix;
 *  - that the build script still owns the variable — a runtime read would let a
 *    launched environment relabel a released binary, which is the failure this
 *    design exists to prevent.
 *
 * Run with `bun test tests/version-footer.test.ts`.
 *
 * @module qialike/version-footer-test
 */

import { describe, expect, test } from 'bun:test'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { versionFooterSuffix, heroVersionCaption } from '../packages/qialike-app/src/version-footer.ts'
import { visualWidth } from '../packages/qialike-app/src/markdown.tsx'
import { HERO_ART_MIN_WIDTH } from '../packages/qialike-app/src/hero-layout.ts'

describe('versionFooterSuffix', () => {
  test('beta and dev append their own word', () => {
    expect(versionFooterSuffix('0.5.3', 'beta')).toBe(' beta')
    expect(versionFooterSuffix('0.5.3', 'dev')).toBe(' dev')
  })

  test('prod appends nothing — the bare version is the release look', () => {
    expect(versionFooterSuffix('0.5.3', 'prod')).toBe('')
  })

  test('a version that already spells the marker out is not repeated', () => {
    // The rule the previous QIALIKE_BETA switch carried: `0.5.2-beta` must not
    // read `0.5.2-beta beta`.
    expect(versionFooterSuffix('0.5.2-beta', 'beta')).toBe('')
    expect(versionFooterSuffix('0.5.2-dev', 'dev')).toBe('')
  })

  test('an unrecognised channel renders as prod rather than inventing a marker', () => {
    // The build is where an invalid QIALIKE_BUILD_MODE is rejected; the runtime
    // mapping stays total.
    // @ts-expect-error -- deliberately outside the closed union
    expect(versionFooterSuffix('0.5.3', 'canary')).toBe('')
    // @ts-expect-error -- deliberately outside the closed union
    expect(versionFooterSuffix('0.5.3', '')).toBe('')
  })

  test('the two channels never cross-contaminate', () => {
    expect(versionFooterSuffix('0.5.2-beta', 'dev')).toBe(' dev')
    expect(versionFooterSuffix('0.5.2-dev', 'beta')).toBe(' beta')
  })
})

describe('heroVersionCaption (the line under the brand mark)', () => {
  const URL = 'https://qialike.com'

  test('the three channels read as the user asked for them', () => {
    // User call, 2026-09-22: `Ver: <version> <channel> . URL: <site>`, the channel
    // spelled as the word itself (`beta` / `dev`), never a glyph.
    expect(heroVersionCaption('0.6.3', 'beta', URL)).toBe(`Ver: 0.6.3 beta . URL: ${URL}`)
    expect(heroVersionCaption('0.6.3', 'dev', URL)).toBe(`Ver: 0.6.3 dev . URL: ${URL}`)
    expect(heroVersionCaption('0.6.3', 'prod', URL)).toBe(`Ver: 0.6.3 . URL: ${URL}`)
  })

  test('a version that already spells the channel is not marked twice', () => {
    // Same rule as the footer: `0.5.2-beta` in beta mode must not read
    // `0.5.2-beta beta`, while a dev-mode build of it still gets its own mark.
    expect(heroVersionCaption('0.5.2-beta', 'beta', URL)).toBe(`Ver: 0.5.2-beta . URL: ${URL}`)
    expect(heroVersionCaption('0.5.2-beta', 'dev', URL)).toBe(`Ver: 0.5.2-beta dev . URL: ${URL}`)
    expect(heroVersionCaption('0.5.2-dev', 'dev', URL)).toBe(`Ver: 0.5.2-dev . URL: ${URL}`)
  })

  test('it stays narrow enough for the brand mark it is centered under', () => {
    // The caption is centered under the wordmark, whose floor is
    // HERO_ART_MIN_WIDTH — so every channel's caption has to fit inside it, and
    // the mark is ASCII, so this app's width table and the terminal agree on it
    // (a glyph like `β` is East-Asian-Ambiguous and drifts the centering there).
    for (const mode of ['beta', 'dev', 'prod'] as const) {
      const line = heroVersionCaption('0.6.3', mode, URL)
      expect(visualWidth(line), `${mode}: ${line}`).toBeLessThanOrEqual(HERO_ART_MIN_WIDTH)
      expect(visualWidth(line)).toBe(line.length)
    }
  })
})

describe('the channel is baked, not read at runtime', () => {
  const src = readFileSync(join(process.cwd(), 'packages/qialike-app/src/index.tsx'), 'utf8')
  const build = readFileSync(join(process.cwd(), 'apps/tui-bin/build.mjs'), 'utf8')

  test('index.tsx derives the suffix from the generated constant', () => {
    expect(src).toContain("from './build-mode.ts'")
    expect(src).toContain('versionFooterSuffix(APP_VERSION, BUILD_MODE)')
    // No ambient READ may decide the channel: that is the whole point of baking.
    // (The variable name itself may appear in prose — only the env read is the
    // hazard, so the assertion targets `process.env`.)
    expect(src).not.toContain('process.env.QIALIKE_BUILD_MODE')
    expect(src).not.toContain('process.env.QIALIKE_BETA')
  })

  test('the build script owns the variable and validates it', () => {
    expect(build).toContain('process.env.QIALIKE_BUILD_MODE')
    expect(build).toContain("const BUILD_MODES = ['beta', 'dev', 'prod']")
    // An invalid value must fail the build instead of silently becoming prod.
    expect(build).toContain('QIALIKE_BUILD_MODE must be one of')
  })

  test('the generated constant holds one of the three channels', () => {
    const generated = join(process.cwd(), 'packages/qialike-app/src/build-mode.ts')
    expect(existsSync(generated)).toBe(true)
    expect(readFileSync(generated, 'utf8')).toMatch(/export const BUILD_MODE = "(beta|dev|prod)"/)
  })
})
