/**
 * Legacy names of the pre-rename product (`dsh-tui`), kept readable so a user
 * who already ran that build keeps their state, settings, and environment.
 *
 * The rename to `qialike` covers the binary, the packages, the product strings,
 * `$DSH_HOME` state files, the settings namespaces, and the environment
 * variables. Everything that lives OUTSIDE the shipped code — files on disk,
 * sections in the user's `settings.yaml`, variables exported by a shell — cannot
 * be migrated by editing source, so this module is the single place that knows
 * the old spellings and the rules for reading them:
 *
 *   - {@link migrateLegacyHomeFiles} renames each old `$DSH_HOME` file to its new
 *     name once (the files are ours; a rename is lossless and reversible), and
 *     {@link homeFilePath} still reads the old name when the rename could not
 *     happen (read-only home, a file locked by another process).
 *   - {@link mirrorLegacyEnv} copies any `DSH_TUI_*` variable to `QIALIKE_*`
 *     before the app reads it, so a shell profile or a wrapper script keeps
 *     working. It runs at module load — several modules read `process.env` at
 *     import time (`index.tsx`'s debug flags, `bin.ts`'s `SPLASH_DELAY_MS`), so
 *     this module must be the FIRST import of every entry point.
 *   - the pre-rename SETTINGS sections (`dsh-tui-llm:`, `dsh-tui-theme:`, …) are
 *     moved into `qialike.json` once by `config.ts`'s `migrateLegacySettings()`.
 *
 * `apps/tui-bin/src/bin.ts` additionally resolves the old package specifier
 * `@yourname/dsh-tui-app` through `LEGACY_PLUGIN_ALIASES` (generated by
 * `apps/tui-bin/build.mjs`), which keeps a user profile overlay written by the
 * pre-rename build loadable without editing it.
 *
 * @module @yourname/qialike-app/legacy-names
 */

import { existsSync, renameSync } from 'node:fs'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'

/** The product's pre-rename name, as it appears inside identifiers. */
export const LEGACY_PRODUCT = 'dsh-tui'

/** Current name of every `$DSH_HOME` file this app owns, with its legacy name. */
export const HOME_FILE_NAMES: readonly (readonly [current: string, legacy: string])[] = [
  ['qialike.json', 'dsh-tui.json'],
  ['qialike.log', 'dsh-tui.log'],
  ['qialike-titles.json', 'dsh-tui-titles.json'],
  ['qialike-activity.json', 'dsh-tui-activity.json'],
  ['qialike-pinned.json', 'dsh-tui-pinned.json'],
  ['qialike-charwidth.json', 'dsh-tui-charwidth.json'],
]

/** The legacy name for one of our files, or `undefined` for a name we never renamed. */
function legacyNameOf(current: string): string | undefined {
  return HOME_FILE_NAMES.find(([name]) => name === current)?.[1]
}

/** Move every legacy `$DSH_HOME` state file onto its current name, once.
 *
 *  A file is only renamed when the current name does NOT exist (an existing
 *  current file always wins, so a second boot never clobbers newer state) and
 *  the legacy file does. Best effort: a failed rename (read-only home, a lock)
 *  leaves the legacy file in place, and {@link homeFilePath} then keeps reading
 *  it.
 *  @returns the current names actually migrated, for the boot log. */
export function migrateLegacyHomeFiles(): string[] {
  const migrated: string[] = []
  for (const [current, legacy] of HOME_FILE_NAMES) {
    const to = dshHomePath(current)
    if (existsSync(to)) continue
    const from = dshHomePath(legacy)
    if (!existsSync(from)) continue
    try {
      renameSync(from, to)
      migrated.push(current)
    } catch { /* read-only or locked home: homeFilePath() falls back */ }
  }
  return migrated
}

/** Absolute path of one of our `$DSH_HOME` files, preferring the current name.
 *
 *  Used instead of a bare `dshHomePath(name)` so a legacy file that could not be
 *  migrated (see {@link migrateLegacyHomeFiles}) is still read. Writes always
 *  target the current name.
 *  @param name - the current file name (see {@link HOME_FILE_NAMES}).
 *  @returns the path to read; the current name when neither file exists. */
export function homeFilePath(name: string): string {
  const current = dshHomePath(name)
  const legacy = legacyNameOf(name)
  if (legacy === undefined || existsSync(current)) return current
  const old = dshHomePath(legacy)
  return existsSync(old) ? old : current
}

/** Like {@link homeFilePath} for a caller that resolves its own directory
 *  (the char-width calibration cache lives in a per-user cache dir).
 *  @param dir - the directory holding the file.
 *  @param name - the current file name (see {@link HOME_FILE_NAMES}).
 *  @returns the path to read. */
export function legacyAwarePath(dir: string, name: string): string {
  const current = `${dir}/${name}`
  const legacy = legacyNameOf(name)
  if (legacy === undefined || existsSync(current)) return current
  const old = `${dir}/${legacy}`
  return existsSync(old) ? old : current
}

/** Prefix of the pre-rename environment variables (`DSH_TUI_*`). */
export const LEGACY_ENV_PREFIX = 'DSH_TUI_'

/** Prefix of the current environment variables (`QIALIKE_*`). */
export const ENV_PREFIX = 'QIALIKE_'

/** Copy every legacy-prefixed environment variable onto its current name.
 *
 *  A variable already set under the current prefix is never overwritten, so an
 *  explicit `QIALIKE_*` always wins over a leftover `DSH_TUI_*`. Exported for
 *  tests; the module-load side effect below already ran it once per process.
 *  @param env - the environment to migrate (defaults to `process.env`).
 *  @returns the current names that were filled in. */
export function mirrorLegacyEnv(env: NodeJS.ProcessEnv = process.env): string[] {
  const filled: string[] = []
  for (const key of Object.keys(env)) {
    if (!key.startsWith(LEGACY_ENV_PREFIX)) continue
    const current = ENV_PREFIX + key.slice(LEGACY_ENV_PREFIX.length)
    if (env[current] !== undefined) continue
    env[current] = env[key]
    filled.push(current)
  }
  return filled
}

// Module-load side effect: every later `process.env.QIALIKE_*` read (including
// module-scope constants in index.tsx and bin.ts) sees a mirrored legacy value.
mirrorLegacyEnv()

