/**
 * The sidebar's version line: `qialike: <version>` plus the build channel.
 *
 * The channel comes from `QIALIKE_BUILD_MODE` **at build time** and is baked into
 * the artifact (`./build-mode.ts`, regenerated by `apps/tui-bin/build.mjs`), so a
 * released binary cannot be relabelled by the environment it is launched in:
 *
 *   - `beta` → `qialike: 0.5.3 beta`
 *   - `dev`  → `qialike: 0.5.3 dev`
 *   - `prod` → `qialike: 0.5.3` (also the unset default)
 *
 * The marker is a separate word rather than a semver pre-release suffix, which is
 * the convention this footer already used (`QIALIKE_BETA=1` appended ` beta`):
 * `--version` keeps printing the bare package version, and only the footer names
 * the channel.
 *
 * @module @yourname/qialike-app/version-footer
 */

/** The build channels the footer distinguishes. */
export type BuildMode = 'beta' | 'dev' | 'prod'

/**
 * The footer suffix for one version and build channel.
 *
 * A version that already spells the marker out shows as-is, so a `0.5.2-beta`
 * build in `beta` mode does not read `0.5.2-beta beta`. This mirrors the rule the
 * previous `QIALIKE_BETA` switch carried. An unrecognised channel renders as
 * `prod` (no suffix) rather than inventing a marker; the build is where an
 * invalid `QIALIKE_BUILD_MODE` is rejected.
 *
 * @param version - the package version shown in the footer.
 * @param mode - the baked build channel.
 * @returns `' beta'`, `' dev'`, or `''`.
 */
export function versionFooterSuffix(version: string, mode: BuildMode): string {
  if (mode === 'beta') return version.includes('beta') ? '' : ' beta'
  if (mode === 'dev') return version.includes('dev') ? '' : ' dev'
  return ''
}
